name: "CLade: Init"
description: Set up CLade CLI

inputs:
  ref:
    description: Git reference of the CLade to use
    required: false
    default: ${{ github.action_ref }}

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        repository: lesomnus/clade
        ref: ${{ inputs.ref }}
        path: ./.clade-src

    - uses: actions/setup-go@v3
      with:
        go-version-file: ./.clade-src/go.mod
        cache-dependency-path: ./.clade-src/go.mod
        cache: true

    - name: Build
      shell: bash
      run: |
        cd ./.clade-src
        go build -o ./clade ./cmd/clade
        cp ./clade $(go env GOPATH)/bin/.

    - name: Env
      shell: bash
      run: |
        _DATE_PREV=$(date '+%Y-%m-%d' -d 'yesterday')
        _DATE_CURR=$(date '+%Y-%m-%d')

        CLADE_CACHE_DIR="/tmp/clade-cache"
        CLADE_CACHE_DIR_PREV="${CLADE_CACHE_DIR}/${_DATE_PREV}"
        CLADE_CACHE_DIR_CURR="${CLADE_CACHE_DIR}/${_DATE_CURR}"

        echo "CLADE_CACHE_DIR_PREV=${CLADE_CACHE_DIR_PREV}" | tee -a $GITHUB_ENV
        echo "CLADE_CACHE_DIR_CURR=${CLADE_CACHE_DIR_CURR}" | tee -a $GITHUB_ENV
        echo "CLADE_CACHE_DIR=${CLADE_CACHE_DIR}"           | tee -a $GITHUB_ENV

        echo "CLADE_CI_DATE_PREV=${_DATE_PREV}" | tee -a $GITHUB_ENV
        echo "CLADE_CI_DATE_CURR=${_DATE_CURR}" | tee -a $GITHUB_ENV

    - uses: actions/cache@v4
      with:
        path: ${{ env.CLADE_CACHE_DIR_PREV }}
        key: clade-cache-${{ env.CLADE_CI_DATE_PREV }}

    - uses: actions/cache@v4
      with:
        path: ${{ env.CLADE_CACHE_DIR_CURR }}
        key: clade-cache-${{ env.CLADE_CI_DATE_CURR }}
