name: "CLade: Outdated"
description: Lists outdated images

outputs:
  references:
    description: Outdated images
    value: ${{ steps.outdated.outputs.references }}

runs:
  using: composite
  steps:
    - id: outdated
      shell: bash
      run: |
        REFERENCES=$(clade outdated --to-json | jq --raw-input . | jq --slurp 'map(select(length > 0))')
        echo ${REFERENCES}
        echo "references=${REFERENCES}" >> $GITHUB_OUTPUT
