name: "CLade: Outdated"
description: Lists outdated images

inputs:
  log-level:
    description: Log level
    required: true
    default: info

outputs:
  references:
    description: Outdated images
    value: ${{ steps.outdated.outputs.references }}

runs:
  using: composite
  steps:
    - id: outdated
      shell: bash
      run: |
        REFERENCES=$(clade --log-level ${{ inputs.log-level }} outdated | jq --raw-input . | jq --slurp --compact-output 'map(select(length > 0))')
        echo ${REFERENCES}
        echo "references=${REFERENCES}" >> $GITHUB_OUTPUT
