name: "CLade: Outdated"
description: Lists outdated images

inputs:
  log-level:
    description: Log level
    required: true
    default: info

outputs:
  plan_name:
    description: Outdated images
    value: ${{ steps.outdated.outputs.references }}

runs:
  using: composite
  steps:
    - id: outdated
      shell: bash
      run: |
        _PLAN_NAME="plan-${{ github.run_id }}-${{ github.run_attempt }}.json"
        clade --log-level ${{ inputs.log-level }} outdated | tee outdated_references
        cat outdated_references | clade --log-level ${{ inputs.log-level }} plan | tee "${_PLAN_NAME}"

        echo "PLAN_NAME=${_PLAN_NAME}" >> $GITHUB_ENV
        echo "plan_name=${_PLAN_NAME}" >> $GITHUB_OUTPUT

    - uses: actions/cache@v3
      with:
        path: ${{ env.PLAN_NAME }}
        key: clade-${{ env.PLAN_NAME }}
