name: clade outdated

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  init:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for reference in $(go run ./cmd/clade outdated); do
            echo build ${reference}
            ${{ env.ACT && 'echo' }} gh workflow run clade-build.yaml \
              --ref "${{ github.ref }}" \
              --field "reference=${reference}" \
              --field "cascade=true"
          done
