name: clade outdated

on:
  workflow_dispatch:
    inputs:
      cascade:
        description: Trigger builds on outdated images
        required: false
        default: false
        type: boolean
      log-level:
        description: Log level
        required: true
        default: info
        type: choice
        options:
          - fatal
          - error
          - warn
          - info
          - debug

  schedule:
    - cron: "0 0 * * *"

jobs:
  outdated:
    runs-on: ubuntu-22.04
    outputs:
      references: ${{ steps.outdated.outputs.references }}
    steps:
      - uses: actions/checkout@v3
      - uses: lesomnus/clade/init@main

      - name: Login GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: outdated
        uses: lesomnus/clade/outdated@main
        with:
          log-level: ${{ inputs.log-level || 'info' }}

      - name: Trigger
        if: ${{ (github.event_name == 'schedule') || inputs.cascade }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo '${{ steps.outdated.outputs.references }}' | jq '.[]' | while read ref; do
            gh workflow run clade-build.yaml \
              --ref "${{ github.ref }}" \
              --field "reference=${ref}" \
              --field "cascade=true"
          done
