name: clade build
run-name: clade build - ${{ inputs.reference }}

on:
  workflow_dispatch:
    inputs:
      reference:
        description: Image reference to build
        required: true
      cascade:
        description: Trigger builds on child images
        required: false
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true

      - name: Login GHCR
        uses: docker/login-action@v2
        if: ${{ !env.ACT }}
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: go run ./cmd/clade build ${{ env.ACT && '--dry-run' }} ${{ github.event.inputs.reference }}

      - name: Push
        run: |
          for reference in $(go run ./cmd/clade tree --depth 1 ${{ github.event.inputs.reference }}); do
            ${{ env.ACT && 'echo' }} docker push ${reference}
          done

      - name: Cascade
        if: ${{ github.event.inputs.cascade }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for reference in $(go run ./cmd/clade tree --strip 1 --depth 1 ${{ github.event.inputs.reference }}); do
            echo build ${reference}
            ${{ env.ACT && 'echo' }} gh workflow run clade-build.yaml \
              --ref "${{ github.ref }}" \
              --field "reference=${reference}" \
              --field "cascade=true"
          done
