name: test

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true

      - run: go test ./...
      - run: go run ./cmd/clade tree
