name: test

on:
  pull_request:
    paths:
      - "**/*.go"
  push:
    paths:
      - "**/*.go"

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true

      - run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
      - uses: codecov/codecov-action@v3

      - run: go run ./cmd/clade tree
